### ISSUE TITLE
Latest version is not available on npm

### ISSUE THREAD

**Issue by kvskranthikumar** [dmtrKovalenko/date-io#446]
The latest version is not available on npm (the current version pointing to 2.8.1) -

https://www.npmjs.com/package/@date-io/date-fns

To overcome this issue we need that latest version 2.9.0 -
```
Type 'typeof DateFnsUtils' is not assignable to type 'new (...args: any) => MuiPickersAdapter<unknown>'.
  Property 'getDaysInMonth' is missing in type 'DateFnsUtils' but required in type 'IUtils<unknown>'.  TS2322
    166 |   return (
    167 |     <Fragment>
  > 168 |       <LocalizationProvider dateAdapter={DateFnsAdapter} locale={getLocal()}>
        |                             ^
    169 |         {props.children}
    170 |       </LocalizationProvider>
    171 |     </Fragment>
```

**Comment by TrejGun** [comment]
same here

**Comment by dmtrKovalenko** [comment]
I don't really understand the problem. Pickers have their own dependency to concrete version – how did you get this error

**Comment by TrejGun** [comment]
the proble you have a roof ^ in version 2.8.0 so it installs 2.9.0

**Comment by TrejGun** [comment]
while we are still waiting for a fix, here is a fast workaround:

`declare module "@material-ui/pickers/adapter/date-fns" {
  export default class DateFnsUtils {
    getDaysInMonth(value: Date): number;
  }
}`

**Comment by FaBeyyy** [comment]
Fix this shit jesus

**Comment by FaBeyyy** [comment]
> I don't really understand the problem. Pickers have their own dependency to concrete version – how did you get this error

Fix this shit...jesus

**Comment by dmtrKovalenko** [comment]
Fixed with 2.9.0, right?

**Comment by kjstauffer** [comment]
The problem is NPM is still referencing 2.8.1. So this issue is still not fixed.

See https://www.npmjs.com/package/@date-io/date-fns

**Comment by FaBeyyy** [comment]
> Fixed with 2.9.0, right?

How are you the maintainer of this if you dont understand this issue. Did someone gift you this github account?

**Comment by TrejGun** [comment]
@dmtrKovalenko nope

**Comment by dmtrKovalenko** [comment]
OK it was really a bug with lerna. Published `@date-io/date-fns` v2.9.1 https://www.npmjs.com/package/@date-io/date-fns
